apis/urls.py
from django.urls import path, include
from . import views
from .views import CMCView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = "apis"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/cmc', CMCView.as_view()),
]
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cds_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
 
app_name = "users"
 
urlpatterns = [
    path('', views.SignUpView.as_view(), name="home"),
    path('sign-in/', views.SignInView.as_view(), name="sign-in"),
    path('sign-out/', views.sign_out, name="sign-out"),
    path('account/', views.AccountView.as_view(), name="account"),
    ]

apis/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4

class CMC(models.Model):
   id = models.UUIDField(primary_key = True,default = uuid4, editable = False)
   inserted_at = models.DateTimeField(default=datetime.utcnow)
   last_updated = models.DateField(default=datetime.utcnow)
   name = models.CharField(max_length=30, default="")
   symbol = models.CharField(max_length=30, default="")
   price = models.FloatField(null=True, default=0.0)
   market_cap = models.BigIntegerField(null=True, default=0.0)
   market_cap_dominance = models.BigIntegerField(null=True, default=0.0)
   fully_diluted_market_cap = models.BigIntegerField(null=True, default=0.0)
   percent_change_1h = models.FloatField(null=True, default=0.0)
   percent_change_24h = models.FloatField(null=True, default=0.0)
   percent_change_30d = models.FloatField(null=True, default=0.0)
   percent_change_60d = models.FloatField(null=True, default=0.0)
   percent_change_7d = models.FloatField(null=True, default=0.0)
   percent_change_90d = models.FloatField(null=True, default=0.0)
   volume_24h = models.FloatField(null=True, default=0.0)
   volume_change_24h = models.FloatField(null=True, default=0.0)

   class Meta:
    unique_together = ('symbol', 'inserted_at',)

   def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import User
from django.db import models
 
class UserProfile(models.Model):
    '''
    Our UserProfile model extends the built-in Django User Model
    This is specific to the user! i.e. the individual that signs up
    '''
    class Meta:
        verbose_name_plural = 'User Profiles'
        ordering = ["id"]
 
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default = False)

users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
)
from django.contrib.auth.models import User
from django import forms
 
 
 
 
class UserForm(UserCreationForm):
    '''
    Form that uses built-in UserCreationForm to handle user creation
    '''
    username = forms.EmailField(max_length=254, required=True,
        widget=forms.TextInput(attrs={
            'placeholder': '*Email..'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': '*Password..',}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': '*Confirm Password..',}))
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', )
 
 
 
 
class AuthForm(AuthenticationForm):
    '''
    Form that uses built-in AuthenticationForm to handle user auth
    '''
    username = forms.EmailField(max_length=254, required=True,
        widget=forms.TextInput(attrs={'placeholder': '*Email..',}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '*Password..',}))
 
    class Meta:
        model = User
        fields = ('username','password', )

apis/views.py
from django.shortcuts import render
from rest_framework import generics
from .models import CMC
from .serializers import CMCSerializer
from django.shortcuts import redirect, reverse
from django.views import generic
from django.contrib.auth import logout
from django.contrib.auth import logout, login, authenticate
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# Create your views here.

class CMCView(generics.ListCreateAPIView):
    queryset = CMC.objects.all()
    serializer_class = CMCSerializer


 

users/views.py
from django.shortcuts import redirect, reverse
from django.views import generic
from django.contrib.auth import logout, login, authenticate
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from . decorators import login_forbidden
 
from .forms import (
    UserForm,
    AuthForm,
    )
 
# from .tasks import create_email
 



class SignUpView(generic.FormView):
 
    template_name = "users/sign_up.html"
    form_class = UserForm
    success_url = "/account/"
 
    def form_valid(self, form):
        obj = form.save()
        login(self.request, obj)
        #this is a celery task
        create_email.delay(
            user_id = obj.id, #user ID - this must be added
            email_account = "do not reply",#the email account being used
            subject = 'Thanks for signing up',
            email = obj.username,#who to email
            cc = [],
            template = "hello.html",#template to be used
            )
        return super().form_valid(form)
   
    @method_decorator(login_forbidden)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
 
 
 
 
class SignInView(generic.FormView):
    '''
    View for user sign in
    '''
    template_name = "users/sign_in.html"
    form_class = AuthForm
    success_url = "/account/"
 
    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(self.request, user)
            return super(SignInView, self).form_valid(form)
        else:
            return self.form_invalid(form)
 
    @method_decorator(login_forbidden)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
 
 
def sign_out(request):
    '''
    Basic view for user sign out
    '''
    logout(request)
    return redirect(reverse('users:sign-in'))
 
 
 

class AccountView(generic.TemplateView):
    '''
    This is the user profile/account view
    '''
    template_name = "users/account.html"
 
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

users/templates/users/accounts.html
{% extends 'users/base.html' %}
{% load static %}
 
{% block content %}
    <div>  
        <p>Welcome to your user account.</p>
        <br>
        <p>A welcome email is on its way.</p>
    </div>
{% endblock %}

users/templates/users/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Did Coding</title>
  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
 
</head>
<body>
 
{% if not request.user.is_authenticated %}
<ul>
  <li><a href="{% url 'users:home' %}">Sign Up</a></li>
  <li><a href="{% url 'users:sign-in' %}">Sign In</a></li>
</ul>
{% else %}
<ul>
  <li><a href="javascript:void(0)">Account</a></li>
  <li style="float:right"><a href="{% url 'users:sign-out' %}">Sign Out</a></li>
</ul>
{% endif %}
<div class="container">
  {% block content %}
  {% endblock %}
</div>
 
</body>
</html>

users/templates/users/sign_in.html
{% extends 'users/base.html' %}
 
{% block content %}
 
    <form method="POST" action="/sign-in/">
    {% csrf_token %}
        <div class="container">
            <h1>Sign In</h1>
            <p>Please fill in this form to Sign In.</p>
            <hr>
 
            <label for="email"><b>Email</b></label>
            {{form.username}}
 
            <label for="psw"><b>Password</b></label>
            {{form.password}}
 
            <hr>
            <button type="submit" class="register btn">Sign In</button>
        </div>
 
        <div class="container signin">
            <p>Don't have an account? <a href="{% url 'users:home' %}">Sign Up</a></a>.</p>
        </div>
    </form>
 
{% endblock %}

users/templates/users/sign_up.html
{% extends 'users/base.html' %}
 
{% block content %}
    <form method="POST" action="/">
    {% csrf_token %}
        <div class="container">
            <h1>Sign Up</h1>
            <p>Please fill in this form to create an account.</p>
            <hr>
 
            <label for="email"><b>Email</b></label>
            {{form.username}}
 
            <label for="psw"><b>Password</b></label>
            {{form.password1}}
 
            <label for="psw-repeat"><b>Repeat Password</b></label>
            {{form.password2}}
            <hr>
            <button type="submit" class="registerbtn">Sign Up</button>
        </div>
 
        <div class="container signin">
            <p>Already have an account? <a href="{% url 'users:sign-in' %}">Sign in</a></a></a></a>.</p>
        </div>
    </form>
{% endblock %}